In [1]:
import numpy as np
import pandas as pd

In [2]:
fighters = pd.read_csv('/Users/amap3i/Library/CloudStorage/OneDrive-GrandValleyStateUniversity/CIS_671/Final Project/fighters_dataset.csv')
fighters.head()

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,highest_match_importance,open_weight_ratio,n_titles,champion,custom_score,n_different_subs,fought_superfight,total_wins,debut_year,female
0,Murilo Santana,0.454545,11.0,0.181818,0.181818,0.090909,7.0,-0.272727,0.000000,1.571429,...,3,0.363636,0,0,-0.165699,1,0,5.0,2009,0
1,Nicholas Meregali,0.750000,8.0,0.125000,0.250000,0.250000,2.0,0.125000,-0.375000,4.000000,...,4,0.500000,0,0,1.977330,1,0,6.0,2022,0
2,Nick Rodriguez,0.700000,10.0,0.100000,0.400000,0.200000,4.0,2.300000,-0.200000,2.500000,...,4,0.200000,0,0,0.854628,1,0,7.0,2019,0
3,Otavio Sousa,0.625000,8.0,0.375000,0.125000,0.125000,4.0,-0.750000,0.500000,2.000000,...,4,0.000000,0,0,0.567981,2,0,5.0,2013,0
4,Orlando Sanchez,0.692308,13.0,0.153846,0.153846,0.384615,8.0,-0.384615,-0.461538,1.625000,...,4,0.000000,1,1,0.424658,2,0,9.0,2013,0

In [3]:
names = fighters['name'].unique()

In [4]:
names

array(['Murilo Santana', 'Nicholas Meregali', 'Nick Rodriguez',
       'Otavio Sousa', 'Orlando Sanchez', 'Pablo Mantovani',
       'Pablo Popovitch', 'Paul Schreiner', 'Paulo Miyao', 'Rida Haisam',
       'Roberto Abreu', 'Roberto Jimenez', 'Robson Moura',
       'Rodolfo Vieira', 'Rodrigo Medeiros', 'Roger Gracie',
       'Romulo Barral', 'Ronaldo Souza', 'Roosevelt Sousa',
       'Adam Wardzinski', 'Braulio Estima', 'Celso Vinicius',
       'Claudio Calasans', 'Bruno Frazatto', 'Craig Jones',
       'Brianna Ste-Marie', 'Dante Leon', 'Davi Ramos', 'David Terrell',
       'Demian Maia', 'Diego Oliveira', 'Diogo Reis', 'Eddie Bravo',
       'Dean Lister', 'DeAlonzio Jackson', 'Gabriel Arges',
       'Gabriel Sousa', 'Gary Tonon', 'Giancarlo Bodoni', 'Gianni Grippo',
       'Gilbert Burns', 'Gordon Ryan', 'Justin Rader', 'Keenan Cornelius',
       'Kron Gracie', 'Lucas Lepri', 'Lucas Daniel Barbosa',
       'Matheus Diniz', 'Matheus Gabriel Barros', 'Marcio Feitosa',
       'Marcus Almeida', 'Rafael Mendes', 'Renato Forasieppi Canuto',
       'Ryan Hall', 'Tye Ruotolo', 'Tim Spriggs', 'Patrick Gaudio',
       'Yuri Simoes', 'Geovanny Martinez', 'Jared Dopp', 'Mahamed Aly',
       'Mansher Khera', 'Abdurakhman Bilarov', 'AJ Agazarm',
       'Alexandre Ribeiro', 'Amy Campo', 'Andre Galvao', 'Augusto Mendes',
       'Baret Yoshida', 'Elder Cruz', 'Fabricio Andrey',
       'Fabricio Werdum', 'Ffion Davies', 'Felipe Pena', 'Jackson Sousa',
       'James Puopolo', 'Jake Shields', 'Jean Jacques Machado',
       'Joao Miyao', 'Joao Gabriel Rocha', 'Joao Assis', 'Jon Blank',
       'Jose Mario Sperry', 'Josh Hinger', 'Joshua Cisneros',
       'Jonathan Torres', 'Kade Ruotolo', 'Kaynan Duarte',
       'Kennedy Maciel', 'Kyle Boehm', 'Lachlan Giles', 'Leonardo Santos',
       'Leonardo Vieira', 'Marcelo Garcia', 'Marcio Cruz', 'Mason Fowler',
       'Matt Serra', 'Micael Galvao', 'Rafael Lovato Jr',
       'Rafaela Guedes', 'Rany Yahya', 'Renzo Gracie', 'Ricardo Almeida',
       'Ricardo Arona', 'Ricardo Liborio', 'Richard Alarcon',
       'Rousimar Palhares', 'Royler Gracie', 'Rubens Charles',
       'Sam McNally', 'Saulo Ribeiro', 'Sergio Moraes', 'Tarsis Humpreys',
       'Vagner Rocha', 'Victor Estima', 'Victor Hugo',
       'Vinicius Ferreira', 'Vinicius Magalhaes', 'Vitor Ribeiro',
       'Bianca Basilio', 'Max Gimenis', 'Jeff Glover', 'Jeremy Skinner',
       'Marcelo Mafra', 'Nicky Ryan', 'Aaron Johnson', 'Rigan Machado',
       'Gabrielle Garcia', 'Mackenzie Dern', 'Antonio Braga Neto',
       'Lucas Leite', 'Victor Honorio', 'Ricco Rodriguez', 'Dillon Danis',
       'Alexandre de Freitas', 'Abraham Marte Messina',
       'Antonio Schembri', 'Amaury Bitetti', 'Eduardo Telles',
       'Ethan Crelinsten', 'Jorge Patino', 'Kendall Reusing',
       'Leonardo Nogueira', 'Marcio Andre Barbosa Junior',
       'Pedro Marinho', 'Ricardo Vieira', 'Roberto Traven',
       'Rodrigo Gracie', 'Cassio Francis', 'Marcio Corleta',
       'Rodrigo Cavaca', 'Edward Cummings', 'Roberto Magalhaes',
       'Gregor Gracie', 'Flavio Almeida', 'Beatriz Mesquita',
       'Gabriel Rollo', 'Bianca Mesquita', 'Vitor Viana',
       'Glover Teixeira', 'Jessica Oliveira', 'Ruslam Chsiev',
       'Sean Alvarez', 'Mark Kerr', 'Mark Robinson', 'Vitor Belfort',
       'Gabriel Napao', 'John Hansen', 'A. Cacareco', 'David Avellan',
       'Eoghan OFlannagan', 'Ana Carolina Vieira', 'Robert Drysdale',
       'Garth Taylor', 'Kareem Barkalev', 'Sasha Palvski', 'Jeff Monson',
       'Kamil Uminski', 'Chael Sonnen', 'Rolles Gracie',
       'Eoghan Oflanagan', 'Egan Inoue', 'Murilo Bustamante',
       'Rustam Chsiev', 'Matt Hughes', 'Sasha Savko', 'Olav Einemo',
       'Tito Ortiz', 'Kyle Griffin', 'Mike Fowler', 'Sanae Kikuta',
       'Mateusz Szczecinski', 'Nicolas Renier', 'Oskar Piechota',
       'E. Karpinen', 'Kuba Witkowski', 'Gunnar Nelson', 'Hayato Sakurai',
       'Henrique Cardoso', 'Andy Varela', 'Thomas Halpin',
       'Tommy Langaker', 'Michael Perez', 'Enrico Cocco', 'Edwin Najmi',
       'Gabriel Lucas', 'Jonathan Satava', 'Keith Krikorian',
       'Leonardo Saggioro', 'John Combs', 'Alec Baulding',
       'Ruan Alvarenga', 'Isaque Bahiense', 'Gabriel Marangoni',
       'Clark Gracie', 'Perttu Tepponen', 'Santeri Lilius', 'Oliver Taza',
       'Alexandre Vieira', 'Sergio Ardila-Ibarra', 'John Salter',
       'Elisabeth Clay', 'Cole Abate', 'Alexander Trans',
       'Roberto Alencar', 'Paul Ardila-Ibarra', 'Gabriel Almeida',
       'Ross Nicholls', 'Eldar Rafigaev', 'Devhonte Johnson',
       'Valdir Araujo Junior', 'Alexandre Jesus',
       'Eleftheria Christodoulou', 'Ashley Williams', 'Yuta Shimada',
       'Kit Dale', 'Felipe Cesar', 'Shane Hill-Taylor', 'Leandro Lo',
       'Joao Costa', 'Servio Tulio', 'James Brasco',
       'Jose Mario Queiroga', 'Gerardi Rinaldi', 'Antonio Peinado',
       'Shinya Aoki', 'Christian Moriarty', 'Ryan Gracie',
       'Talita Alencar', 'Mark Ramos', 'Gustavo Dantas',
       'Augusto Ferrari', 'Radoslaw Turek', 'Penny Thomas',
       'Amanda Alequin / Santana', 'Michelle Nicolini', 'Carlos Machado',
       'Fellipe Andrew', 'E. Karppinen', 'Igor Praporschchikov',
       'Tomas Szczerek', 'Yuji Arai', 'Janne-Pekka', 'Daniel Strauss',
       'M. Perez', 'Elvira Karpinnen', 'Julia Maele', 'Ben Dyson',
       'Elvira Karppinen', 'Magid Hage', 'M. Szczecinski', 'Young-Ahm',
       'Akira Shoji', 'Marko Helen', 'Yushin Okami', 'M. Yano',
       'Ilir Lafiti', 'Nate Marquardt', 'Andreas Olsen', 'Jia Jang',
       'Ezra Lenon', 'Hideki Sekine', 'Lee Hyoung', 'Ricardo Mesquita',
       'Hannette Staack', 'Yurika Nakakura', 'Tammy Griego',
       'Fernanda Mazelli', 'Alison Tremblay', 'Amanda Santana',
       'Talita Treta', 'Stefanie Egger', 'Ana Carolina', 'Carina Santi',
       'Satori Kitaoka', 'Eoghan OFlanagan', 'Ben Hodgkinson',
       'Heikki Jussila', 'Timo-Juhani', 'Erza Lennon', 'J. Urholin',
       'Piotr Frechowicz', 'Erico Cocco', 'Jason Manly', 'Andy Wang',
       'Tero Pyylampi', 'Gamrot Mateusz', 'Osman Kasimov', 'Kethe Engen',
       'Bia Mesquita', 'Rodrigo Dib', 'Josh Hayden', 'Caol Uno',
       'Peter Angerer', 'F. Vasconcelos', 'Urija Faber',
       'Jimmy Freidrich', 'A. Zhanpeisov', 'Y. Takahito', 'Tetsu Suzuki',
       'Jeff Curran', 'Tetsu Hadario', 'J. Pietkainen', 'Zbigniew Tyszka',
       'Hideki Shrek', 'Elliot Marshal', 'Luke Griffith', 'Kamil Wilk',
       'Jesseray Childrey', 'Amir Allam', 'Abdulaev Ruslan',
       'Eliott Kelly', 'Jon Hansen', 'Yousef Elzien', 'Ricardo Moraes',
       'Firas Nakdali', 'Rocky Batastini', 'Kim Mason', 'Carlos Barreto',
       'Y. Yatso', 'Halm Gocalli', 'Y. Ozawa', 'Juskowiak Mateusz',
       'Trevor Lally', 'Marc', 'Robin Gracie', 'T. Hirono',
       'Sasha Plavski', 'Joe Gilbert', 'Y. Kinishi', 'K. Hirate',
       'Joaquim Hansen', 'Erik Paulson', 'Michael Groth',
       'Jamal Peterson', 'John Einimo', 'Antoine Joude', 'Yukissyu Ozawa',
       'Tim Carpenter', 'Ilir Latifi', 'Lucio Lagarto', 'Yukiyasu Ozawa',
       'T. Pyylampi', 'Wellington Dias', 'Akira Shouji', 'Chris Bright',
       'Mark Bocek', 'Kassim Anan', 'Chris Weidman', 'Tom Bass',
       'Don Ortega', 'Shinzo Ansai', 'Akihiro Gono', 'Alexander Savko',
       'Nicholas Renier', 'N. Uematsu', 'Mike Mrkulic', 'Eddie Sanchez',
       'Yoshitomi Mishima', 'Tetsu Suzuko', 'Rikako Yuasa',
       'Nicollas Renier', 'T. Kosaka', 'Jehad Hamdan', 'Mike Van',
       'Matt Lindland', 'Denis Roberts', 'Daniel Simoes', 'Reese Andy',
       'Mario Rinaldi', 'Elvis Sinosic', 'Darren Andy', 'Rogent Lorent',
       'Tomasz Janiszewski', 'Jimmy Friedrich', 'Josh Saunders',
       'Paulo Pinto', 'Diego Sanchez', 'Cameron Earle', 'Micah Pittman',
       'Mikey Burnet', 'Serguei Onishuk', 'Y. Kohsaka', 'Jamie Ballard',
       'Daniel Hortegas', 'James Poupolo', 'Liu Wen', 'Tomasz Narkun',
       'Michael Wilson', 'Jason Lees', 'Eduardo Rios', 'Fabio Gurgel',
       'Karl Webber', 'Egan Inoe', 'Take Hanai', 'Muhammad Saleh',
       'Larry Parker', 'Renato Verissimo', 'Oleg Taktarov', 'Simon Siasi',
       'Enson Inoe', 'Keita Iwamoto', 'Owen Livesey', 'Giovanna Jara',
       'Cristiano Lazzarini', 'R. Alvarenga', 'Alian Drueco',
       'Mikael Knutsson', 'George St', 'Yoshiyuki Yoshida',
       'Morris Clifoni', 'Allan Teo', 'T. Suzuki', 'Joey Gilbert',
       'Rob Di', 'D. Marinakis', 'Sotaro Yamada', 'Rodney Ellis',
       'Bruno Bastos', 'Marcos Oliveira', 'Anthony Perosh',
       'Kiuma Kunioku', 'Mario Miranda', 'George Sotiropoulos',
       'Kurt Pellegrino', 'Keita Nakamura', 'Robert Sabaruddin',
       'Van Arsdale', 'Mike Whitehead', 'Alex Negao', 'Miodrag Petkovic',
       'J. Pietlainen', 'Takanori Gomi', 'Thomas DeBlass', 'Jorge Britto',
       'Keller Sodhi', 'Youngnam Noh', 'Ben Henderson', 'Kitner Mendoga',
       'H. Sekine', 'Mateusz Juskowiak', 'E. Elgland', 'Eric Dahlberg',
       'Ben Askren', 'Doorwang Jeon', 'Janus Andrejczuk', 'Kenta Iwamoto',
       'Wagnney Fabiano', 'Jacob Rodriguez', 'Tom Lawlor', 'Jeon Doo',
       'Shinsho Anzai', 'Hidemi Mihara', 'Abdulkadirov Magomed',
       'Perttu Terpponnen', 'Teemu Launis', 'Mario Delgado',
       'Darrel Moodley', 'Kouhei Yasumi', 'Frank Trigg',
       'Rodrigo Modrias', 'Fabiano Iha', 'Israel Albuquerque',
       'Chris Brown', 'G. Sotiropoulos', 'Josh Barnet', 'Y. Setsenko',
       'Marshurenko', 'M. Van', 'Andy Reese', 'R. Babalu', 'Roger Neff',
       'Luis Orlando', 'Toshiyuki Oyama', 'Yuta Sasaki', 'Travis Lutter',
       'Jerry Bolander', 'Pete Williams', 'Yuki Ozawa', 'Asa Fuller',
       'Sekine Hideki', 'Mike Martelle', 'Kamil Huminski',
       'Khazmat Stambulov', 'Jurie Rachel', 'Luis Roberto',
       'Hiroyuko Abe', 'Joe Guilbert', 'Greger Forsel', 'Joseph Lee',
       'Adrian Serrano', 'Carlos Newton', 'Ahmad Faraj', 'Gavin Kulper',
       'Nathan Marquardt', 'Justin Garcia', 'Jon Einemo', 'Travers Grubb',
       'Kim Dong', 'C. Jones', 'Nieman Gracie', 'David Bielkheden',
       'Dennis Hallman', 'Joao Roque', 'James Harbison', 'Dan Schon',
       'Juan Valles', 'Melchor M.', 'A. Hamlet', 'Martin Brown',
       'Mike Cardosa', 'Charles Pearson', 'Hiroshi Nakamura',
       'Joel Tudor', 'David Marinakis', 'Tezekbaev Rasul',
       'U. Zhakshylyk', 'Vernon White', 'Dave Menne', 'R. Anderson',
       'T. Yano', 'Yuki Sasaki', 'L. Papadopoulis', 'Kouji Kanechika',
       'Jorge Santiago', 'I. Praporshchikov', 'Jose Junior',
       'Milton Vieira', 'Isaak Michel', 'Sanshiro Nakamura',
       'Chris Wideman', 'Luke Costello', 'Wang Yan', 'P. Ardilla',
       'Rumina Sato', 'Fernando Vieira', 'Hanette Staack',
       'Jessica Flowers', 'Akira Soji', 'Otto Olsen', 'Renan Sancar',
       'Mateusz Garmot', 'Kaynan D.', 'Jayson Patino', 'Mraz Avdoyan',
       'Rodrigo Minotauro', 'Tobias G', 'Kari Petola', 'Adele Fornarino',
       'Ryan Harvey', 'Tom Barlow', 'Janne Pietilainen', 'Ricardo Alves',
       'Sim Go', 'Jason White', 'Damon Ramos', 'Roan Jucao',
       'Bruno Chavez', 'Luis Brito', 'Fan Yi', 'H. Kanehara',
       'R. Mashurenko', 'Tamura', 'Hudson Taylor', 'F. Capoane',
       'Adam Sachnoff', 'Genki Sudo', 'Robert Sulski', 'J. Wakabayashi',
       'D. Hemmings', 'Takefuni Hanai', 'Dan Manasoiu', 'Livia Giles',
       'Roman Dolidze', 'Hector Lombard', 'Asadulaev Surkhay',
       'Marcio Cromado', 'Bob Schirmer', 'Chris Brennan', 'Gao Hua',
       'Mourat Ozov', 'Rodrigo Artilheiro', 'K. Toida', 'Davis Heart',
       'Davion Peterson', 'Manu Garcia', 'Dan Martinez', 'Jason Brudvik',
       'Jason Ramsterrer', 'Jesse Urholin', 'Amanda Leve',
       'Rodrigo Caporal', 'William Tackett', 'Mayssa Bastos'],
      dtype=object)

In [5]:
# Refined list with state information where applicable
fighters_info = [
    {"name": "Murilo Santana", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Nicholas Meregali", "city": "Santo Antônio da Patrulha", "state": "NaN", "country": "Brazil"},
  {"name": "Nick Rodriguez", "city": "Philadelphia", "state": "Pennsylvania", "country": "USA"},
  {"name": "Otavio Sousa", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Orlando Sanchez", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Pablo Mantovani", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Pablo Popovitch", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Paul Schreiner", "city": "Santa Cruz", "state": "California", "country": "USA"},
  {"name": "Paulo Miyao", "city": "Andirá", "state": "NaN", "country": "Brazil"},
  {"name": "Rida Haisam", "city": "Accra", "state": "NaN", "country": "Ghana"},
  {"name": "Roberto Abreu", "city": "Campo Grande", "state": "NaN", "country": "Brazil"},
  {"name": "Roberto Jimenez", "city": "Guayaquil", "state": "NaN", "country": "Ecuador"},
  {"name": "Robson Moura", "city": "Teresópolis", "state": "NaN", "country": "Brazil"},
  {"name": "Rodolfo Vieira", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Rodrigo Medeiros", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Roger Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Romulo Barral", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Ronaldo Souza", "city": "Vila Velha", "state": "NaN", "country": "Brazil"},
  {"name": "Roosevelt Sousa", "city": "Natal", "state": "NaN", "country": "Brazil"},
  {"name": "Adam Wardzinski", "city": "Poznań", "state": "NaN", "country": "Poland"},
  {"name": "Braulio Estima", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Celso Vinicius", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Claudio Calasans", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Bruno Frazatto", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Craig Jones", "city": "Adelaide", "state": "NaN", "country": "Australia"},
  {"name": "Brianna Ste-Marie", "city": "Montreal", "state": "NaN", "country": "Canada"},
  {"name": "Dante Leon", "city": "Windsor", "state": "NaN", "country": "Canada"},
  {"name": "Davi Ramos", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "David Terrell", "city": "Santa Rosa", "state": "California", "country": "USA"},
  {"name": "Demian Maia", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Diego Oliveira", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Diogo Reis", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Eddie Bravo", "city": "Santa Ana", "state": "California", "country": "USA"},
  {"name": "Dean Lister", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "DeAlonzio Jackson", "city": "Chicago", "state": "Illinois", "country": "USA"},
  {"name": "Gabriel Arges", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Gabriel Sousa", "city": "Fortaleza", "state": "NaN", "country": "Brazil"},
  {"name": "Gary Tonon", "city": "New Brunswick", "state": "New Jersey", "country": "USA"},
  {"name": "Giancarlo Bodoni", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Gianni Grippo", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Gilbert Burns", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Gordon Ryan", "city": "Monroe Township", "state": "New Jersey", "country": "USA"},
  {"name": "Justin Rader", "city": "Oklahoma City", "state": "Oklahoma", "country": "USA"},
  {"name": "Keenan Cornelius", "city": "Hilo", "state": "Hawaii", "country": "USA"},
  {"name": "Kron Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Lucas Lepri", "city": "Uberlândia", "state": "NaN", "country": "Brazil"},
  {"name": "Lucas Daniel Barbosa", "city": "Boa Vista", "state": "NaN", "country": "Brazil"},
  {"name": "Matheus Diniz", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Matheus Gabriel Barros", "city": "João Pessoa", "state": "NaN", "country": "Brazil"},
  {"name": "Marcio Feitosa", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Marcus Almeida", "city": "Santos", "state": "NaN", "country": "Brazil"},
  {"name": "Rafael Mendes", "city": "Rio Claro", "state": "NaN", "country": "Brazil"},
  {"name": "Renato Forasieppi Canuto", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Ryan Hall", "city": "Falls Church", "state": "Virginia", "country": "USA"},
  {"name": "Tye Ruotolo", "city": "Huntington Beach", "state": "California", "country": "USA"},
  {"name": "Tim Spriggs", "city": "Baltimore", "state": "Maryland", "country": "USA"},
  {"name": "Patrick Gaudio", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Yuri Simoes", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Geovanny Martinez", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Jared Dopp", "city": "Oklahoma City", "state": "Oklahoma", "country": "USA"},
  {"name": "Mahamed Aly", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Mansher Khera", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Abdurakhman Bilarov", "city": "Makhachkala", "state": "NaN", "country": "Russia"},
  {"name": "AJ Agazarm", "city": "Cleveland", "state": "Ohio", "country": "USA"},
  {"name": "Alexandre Ribeiro", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Amy Campo", "city": "Ogden", "state": "Utah", "country": "USA"},
  {"name": "Andre Galvao", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Augusto Mendes", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Baret Yoshida", "city": "Honolulu", "state": "Hawaii", "country": "USA"},
  {"name": "Elder Cruz", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Fabricio Andrey", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Fabricio Werdum", "city": "Porto Alegre", "state": "NaN", "country": "Brazil"},
  {"name": "Ffion Davies", "city": "Cardiff", "state": "NaN", "country": "Wales"},
  {"name": "Felipe Pena", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Jackson Sousa", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "James Puopolo", "city": "Salem", "state": "Oregon", "country": "USA"},
  {"name": "Jake Shields", "city": "Summertown", "state": "Tennessee", "country": "USA"},
  {"name": "Jean Jacques Machado", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Joao Miyao", "city": "Andirá", "state": "NaN", "country": "Brazil"},
  {"name": "Joao Gabriel Rocha", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Joao Assis", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Jon Blank", "city": "Bethlehem", "state": "Pennsylvania", "country": "USA"},
  {"name": "Jose Mario Sperry", "city": "Porto Alegre", "state": "NaN", "country": "Brazil"},
  {"name": "Josh Hinger", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Joshua Cisneros", "city": "Fresno", "state": "California", "country": "USA"},
  {"name": "Jonathan Torres", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Kade Ruotolo", "city": "Huntington Beach", "state": "California", "country": "USA"},
  {"name": "Kaynan Duarte", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Kennedy Maciel", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Kyle Boehm", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Lachlan Giles", "city": "Melbourne", "state": "NaN", "country": "Australia"},
  {"name": "Leonardo Santos", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Leonardo Vieira", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Marcelo Garcia", "city": "Formiga", "state": "NaN", "country": "Brazil"},
  {"name": "Marcio Cruz", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Mason Fowler", "city": "Fresno", "state": "California", "country": "USA"},
  {"name": "Matt Serra", "city": "East Meadow", "state": "New York", "country": "USA"},
  {"name": "Micael Galvao", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Rafael Lovato Jr", "city": "Oklahoma City", "state": "Oklahoma", "country": "USA"},
  {"name": "Rafaela Guedes", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Rany Yahya", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Renzo Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Ricardo Almeida", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Ricardo Arona", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Ricardo Liborio", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Richard Alarcon", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Rousimar Palhares", "city": "Dores do Indaiá", "state": "NaN", "country": "Brazil"},
  {"name": "Royler Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Rubens Charles", "city": "São Carlos", "state": "NaN", "country": "Brazil"},
  {"name": "Sam McNally", "city": "Dublin", "state": "NaN", "country": "Ireland"},
  {"name": "Saulo Ribeiro", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Sergio Moraes", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Tarsis Humpreys", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Vagner Rocha", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Victor Estima", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Victor Hugo", "city": "Fortaleza", "state": "NaN", "country": "Brazil"},
  {"name": "Vinicius Ferreira", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Vinicius Magalhaes", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Vitor Ribeiro", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Bianca Basilio", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Max Gimenis", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Jeff Glover", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Jeremy Skinner", "city": "Sydney", "state": "NaN", "country": "Australia"},
  {"name": "Marcelo Mafra", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Nicky Ryan", "city": "Monroe Township", "state": "New Jersey", "country": "USA"},
  {"name": "Aaron Johnson", "city": "Chicago", "state": "Illinois", "country": "USA"},
  {"name": "Rigan Machado", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Gabrielle Garcia", "city": "Porto Alegre", "state": "NaN", "country": "Brazil"},
  {"name": "Mackenzie Dern", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Antonio Braga Neto", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Lucas Leite", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Victor Honorio", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Ricco Rodriguez", "city": "San Jose", "state": "California", "country": "USA"},
  {"name": "Dillon Danis", "city": "Parsippany", "state": "New Jersey", "country": "USA"},
  {"name": "Alexandre de Freitas", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Abraham Marte Messina", "city": "Santo Domingo", "state": "NaN", "country": "Dominican Republic"},
  {"name": "Antonio Schembri", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Amaury Bitetti", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Eduardo Telles", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Ethan Crelinsten", "city": "Montreal", "state": "NaN", "country": "Canada"},
  {"name": "Jorge Patino", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Kendall Reusing", "city": "Huntington Beach", "state": "California", "country": "USA"},
  {"name": "Leonardo Nogueira", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Marcio Andre Barbosa Junior", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Pedro Marinho", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Ricardo Vieira", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Roberto Traven", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Rodrigo Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Cassio Francis", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Marcio Corleta", "city": "Porto Alegre", "state": "NaN", "country": "Brazil"},
  {"name": "Rodrigo Cavaca", "city": "Santos", "state": "NaN", "country": "Brazil"},
  {"name": "Edward Cummings", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Roberto Magalhaes", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Gregor Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Flavio Almeida", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Beatriz Mesquita", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Gabriel Rollo", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Bianca Mesquita", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Vitor Viana", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Glover Teixeira", "city": "Sobrália", "state": "NaN", "country": "Brazil"},
  {"name": "Jessica Oliveira", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Rustam Chsiev", "city": "Vladikavkaz", "state": "NaN", "country": "Russia"},
  {"name": "Sean Alvarez", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Mark Kerr", "city": "Toledo", "state": "Ohio", "country": "USA"},
  {"name": "Mark Robinson", "city": "Durban", "state": "NaN", "country": "South Africa"},
  {"name": "Vitor Belfort", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Gabriel Napao", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "John Hansen", "city": "Milwaukee", "state": "Wisconsin", "country": "USA"},
  {"name": "A. Cacareco", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "David Avellan", "city": "Miami", "state": "Florida", "country": "USA"},
  {"name": "Eoghan OFlanagan", "city": "Dublin", "state": "NaN", "country": "Ireland"},
  {"name": "Ana Carolina Vieira", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Robert Drysdale", "city": "Provo", "state": "Utah", "country": "USA"},
  {"name": "Garth Taylor", "city": "Santa Cruz", "state": "California", "country": "USA"},
  {"name": "Kareem Barkalev", "city": "Haifa", "state": "NaN", "country": "Israel"},
  {"name": "Sasha Palvski", "city": "Minsk", "state": "NaN", "country": "Belarus"},
  {"name": "Jeff Monson", "city": "Saint Paul", "state": "Minnesota", "country": "USA"},
  {"name": "Kamil Uminski", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Chael Sonnen", "city": "West Linn", "state": "Oregon", "country": "USA"},
  {"name": "Rolles Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Eoghan Oflanagan", "city": "Dublin", "state": "NaN", "country": "Ireland"},
  {"name": "Egan Inoue", "city": "Honolulu", "state": "Hawaii", "country": "USA"},
  {"name": "Murilo Bustamante", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Rustam Chsiev", "city": "Vladikavkaz", "state": "NaN", "country": "Russia"},
  {"name": "Matt Hughes", "city": "Hillsboro", "state": "Illinois", "country": "USA"},
  {"name": "Sasha Savko", "city": "Minsk", "state": "NaN", "country": "Belarus"},
  {"name": "Olav Einemo", "city": "Oslo", "state": "NaN", "country": "Norway"},
  {"name": "Tito Ortiz", "city": "Huntington Beach", "state": "California", "country": "USA"},
  {"name": "Kyle Griffin", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Mike Fowler", "city": "Virginia Beach", "state": "Virginia", "country": "USA"},
  {"name": "Sanae Kikuta", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Mateusz Szczecinski", "city": "Wrocław", "state": "NaN", "country": "Poland"},
  {"name": "Nicolas Renier", "city": "Paris", "state": "NaN", "country": "France"},
  {"name": "Oskar Piechota", "city": "Gdańsk", "state": "NaN", "country": "Poland"},
  {"name": "E. Karpinen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Kuba Witkowski", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Gunnar Nelson", "city": "Reykjavík", "state": "NaN", "country": "Iceland"},
  {"name": "Hayato Sakurai", "city": "Ibaraki", "state": "NaN", "country": "Japan"},
  {"name": "Henrique Cardoso", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Andy Varela", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Thomas Halpin", "city": "Limerick", "state": "NaN", "country": "Ireland"},
  {"name": "Tommy Langaker", "city": "Bergen", "state": "NaN", "country": "Norway"},
  {"name": "Michael Perez", "city": "San Juan", "state": "NaN", "country": "Puerto Rico"},
  {"name": "Enrico Cocco", "city": "Miami", "state": "Florida", "country": "USA"},
  {"name": "Edwin Najmi", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Gabriel Lucas", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Jonathan Satava", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Keith Krikorian", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Leonardo Saggioro", "city": "Juiz de Fora", "state": "NaN", "country": "Brazil"},
  {"name": "John Combs", "city": "Boulder", "state": "Colorado", "country": "USA"},
  {"name": "Alec Baulding", "city": "Atlanta", "state": "Georgia", "country": "USA"},
  {"name": "Ruan Alvarenga", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Isaque Bahiense", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Gabriel Marangoni", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Clark Gracie", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Perttu Tepponen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Santeri Lilius", "city": "Turku", "state": "NaN", "country": "Finland"},
  {"name": "Oliver Taza", "city": "Beirut", "state": "NaN", "country": "Lebanon"},
  {"name": "Alexandre Vieira", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Sergio Ardila-Ibarra", "city": "Bogotá", "state": "NaN", "country": "Colombia"},
  {"name": "John Salter", "city": "Birmingham", "state": "Alabama", "country": "USA"},
  {"name": "Elisabeth Clay", "city": "Anchorage", "state": "Alaska", "country": "USA"},
  {"name": "Cole Abate", "city": "Austin", "state": "Texas", "country": "USA"},
  {"name": "Alexander Trans", "city": "Aarhus", "state": "NaN", "country": "Denmark"},
  {"name": "Roberto Alencar", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Paul Ardila-Ibarra", "city": "Bogotá", "state": "NaN", "country": "Colombia"},
  {"name": "Gabriel Almeida", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Ross Nicholls", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Eldar Rafigaev", "city": "Moscow", "state": "NaN", "country": "Russia"},
  {"name": "Devhonte Johnson", "city": "Newark", "state": "New Jersey", "country": "USA"},
  {"name": "Valdir Araujo Junior", "city": "Salvador", "state": "NaN", "country": "Brazil"},
  {"name": "Alexandre Jesus", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Eleftheria Christodoulou", "city": "Athens", "state": "NaN", "country": "Greece"},
  {"name": "Ashley Williams", "city": "Swansea", "state": "NaN", "country": "Wales"},
  {"name": "Yuta Shimada", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Kit Dale", "city": "Melbourne", "state": "NaN", "country": "Australia"},
  {"name": "Felipe Cesar", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Shane Hill-Taylor", "city": "Baltimore", "state": "Maryland", "country": "USA"},
  {"name": "Leandro Lo", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Joao Costa", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Servio Tulio", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "James Brasco", "city": "Miami", "state": "Florida", "country": "USA"},
  {"name": "Jose Mario Queiroga", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Gerardi Rinaldi", "city": "Rome", "state": "NaN", "country": "Italy"},
  {"name": "Antonio Peinado", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Shinya Aoki", "city": "Shizuoka", "state": "NaN", "country": "Japan"},
  {"name": "Christian Moriarty", "city": "Dublin", "state": "NaN", "country": "Ireland"},
  {"name": "Ryan Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Talita Alencar", "city": "Fortaleza", "state": "NaN", "country": "Brazil"},
  {"name": "Mark Ramos", "city": "Chicago", "state": "Illinois", "country": "USA"},
  {"name": "Gustavo Dantas", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Augusto Ferrari", "city": "Porto Alegre", "state": "NaN", "country": "Brazil"},
  {"name": "Radoslaw Turek", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Penny Thomas", "city": "Cape Town", "state": "NaN", "country": "South Africa"},
  {"name": "Amanda Alequin / Santana", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Michelle Nicolini", "city": "Itu", "state": "NaN", "country": "Brazil"},
  {"name": "Carlos Machado", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Fellipe Andrew", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "E. Karppinen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Igor Praporschchikov", "city": "Moscow", "state": "NaN", "country": "Russia"},
  {"name": "Tomas Szczerek", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Yuji Arai", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Janne-Pekka", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Daniel Strauss", "city": "London", "state": "NaN", "country": "England"},
  {"name": "M. Perez", "city": "San Juan", "state": "NaN", "country": "Puerto Rico"},
  {"name": "Elvira Karpinnen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Julia Maele", "city": "Oslo", "state": "NaN", "country": "Norway"},
  {"name": "Ben Dyson", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Elvira Karppinen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Magid Hage", "city": "Beirut", "state": "NaN", "country": "Lebanon"},
  {"name": "M. Szczecinski", "city": "Poznań", "state": "NaN", "country": "Poland"},
  {"name": "Young-Ahm", "city": "Seoul", "state": "NaN", "country": "South Korea"},
  {"name": "Akira Shoji", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Marko Helen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Yushin Okami", "city": "Kanagawa", "state": "NaN", "country": "Japan"},
  {"name": "M. Yano", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Ilir Lafiti", "city": "Malmö", "state": "NaN", "country": "Sweden"},
  {"name": "Nate Marquardt", "city": "Lander", "state": "Wyoming", "country": "USA"},
  {"name": "Andreas Olsen", "city": "Copenhagen", "state": "NaN", "country": "Denmark"},
  {"name": "Jia Jang", "city": "Beijing", "state": "NaN", "country": "China"},
  {"name": "Ezra Lenon", "city": "St. Louis", "state": "Missouri", "country": "USA"},
  {"name": "Hideki Sekine", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Lee Hyoung", "city": "Seoul", "state": "NaN", "country": "South Korea"},
  {"name": "Ricardo Mesquita", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Hannette Staack", "city": "São Luís", "state": "NaN", "country": "Brazil"},
  {"name": "Yurika Nakakura", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Tammy Griego", "city": "Albuquerque", "state": "New Mexico", "country": "USA"},
  {"name": "Fernanda Mazelli", "city": "Guarapari", "state": "NaN", "country": "Brazil"},
  {"name": "Alison Tremblay", "city": "Montreal", "state": "NaN", "country": "Canada"},
  {"name": "Amanda Santana", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Talita Treta", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Stefanie Egger", "city": "Bern", "state": "NaN", "country": "Switzerland"},
  {"name": "Carina Santi", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Satori Kitaoka", "city": "Nagasaki", "state": "NaN", "country": "Japan"},
  {"name": "Ben Hodgkinson", "city": "Perth", "state": "NaN", "country": "Australia"},
  {"name": "Heikki Jussila", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Timo-Juhani", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Erza Lennon", "city": "St. Louis", "state": "Missouri", "country": "USA"},
  {"name": "J. Urholin", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Piotr Frechowicz", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Erico Cocco", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Jason Manly", "city": "San Francisco", "state": "California", "country": "USA"},
  {"name": "Andy Wang", "city": "Kaohsiung", "state": "NaN", "country": "Taiwan"},
  {"name": "Tero Pyylampi", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Gamrot Mateusz", "city": "Poznań", "state": "NaN", "country": "Poland"},
  {"name": "Osman Kasimov", "city": "Baku", "state": "NaN", "country": "Azerbaijan"},
  {"name": "Kethe Engen", "city": "Oslo", "state": "NaN", "country": "Norway"},
  {"name": "Bia Mesquita", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Rodrigo Dib", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Josh Hayden", "city": "Louisville", "state": "Kentucky", "country": "USA"},
  {"name": "Caol Uno", "city": "Kanagawa", "state": "NaN", "country": "Japan"},
  {"name": "Peter Angerer", "city": "Munich", "state": "NaN", "country": "Germany"},
  {"name": "F. Vasconcelos", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Urija Faber", "city": "Isla Vista", "state": "California", "country": "USA"},
  {"name": "Jimmy Freidrich", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "A. Zhanpeisov", "city": "Almaty", "state": "NaN", "country": "Kazakhstan"},
  {"name": "Y. Takahito", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Tetsu Suzuki", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Jeff Curran", "city": "Crystal Lake", "state": "Illinois", "country": "USA"},
  {"name": "Tetsu Hadario", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "J. Pietkainen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Zbigniew Tyszka", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Hideki Shrek", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Elliot Marshal", "city": "Boulder", "state": "Colorado", "country": "USA"},
  {"name": "Luke Griffith", "city": "Cape Town", "state": "NaN", "country": "South Africa"},
  {"name": "Kamil Wilk", "city": "Kraków", "state": "NaN", "country": "Poland"},
  {"name": "Jesseray Childrey", "city": "Richmond", "state": "Virginia", "country": "USA"},
  {"name": "Amir Allam", "city": "Cairo", "state": "NaN", "country": "Egypt"},
  {"name": "Abdulaev Ruslan", "city": "Makhachkala", "state": "NaN", "country": "Russia"},
  {"name": "Eliott Kelly", "city": "Sacramento", "state": "California", "country": "USA"},
  {"name": "Jon Hansen", "city": "Salt Lake City", "state": "Utah", "country": "USA"},
  {"name": "Yousef Elzien", "city": "Amman", "state": "NaN", "country": "Jordan"},
  {"name": "Ricardo Moraes", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Firas Nakdali", "city": "Damascus", "state": "NaN", "country": "Syria"},
  {"name": "Rocky Batastini", "city": "San Francisco", "state": "California", "country": "USA"},
  {"name": "Kim Mason", "city": "Sydney", "state": "NaN", "country": "Australia"},
  {"name": "Carlos Barreto", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Y. Yatso", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Halm Gocalli", "city": "Istanbul", "state": "NaN", "country": "Turkey"},
  {"name": "Y. Ozawa", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Juskowiak Mateusz", "city": "Poznań", "state": "NaN", "country": "Poland"},
  {"name": "Trevor Lally", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Marc", "city": "Paris", "state": "NaN", "country": "France"},
  {"name": "Robin Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "T. Hirono", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Sasha Plavski", "city": "Minsk", "state": "NaN", "country": "Belarus"},
  {"name": "Joe Gilbert", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Y. Kinishi", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "K. Hirate", "city": "Nagoya", "state": "NaN", "country": "Japan"},
  {"name": "Joaquim Hansen", "city": "Lisbon", "state": "NaN", "country": "Portugal"},
  {"name": "Erik Paulson", "city": "Chicago", "state": "Illinois", "country": "USA"},
  {"name": "Michael Groth", "city": "Berlin", "state": "NaN", "country": "Germany"},
  {"name": "Jamal Peterson", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "John Einimo", "city": "Oslo", "state": "NaN", "country": "Norway"},
  {"name": "Antoine Joude", "city": "Beirut", "state": "NaN", "country": "Lebanon"},
  {"name": "Yukissyu Ozawa", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Tim Carpenter", "city": "Philadelphia", "state": "Pennsylvania", "country": "USA"},
  {"name": "Ilir Latifi", "city": "Malmö", "state": "NaN", "country": "Sweden"},
  {"name": "Lucio Lagarto", "city": "Salvador", "state": "NaN", "country": "Brazil"},
  {"name": "Yukiyasu Ozawa", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Genki Sudo", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Robert Sulski", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "J. Wakabayashi", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "D. Hemmings", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Takefuni Hanai", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Dan Manasoiu", "city": "Bucharest", "state": "NaN", "country": "Romania"},
  {"name": "Livia Giles", "city": "Sydney", "state": "NaN", "country": "Australia"},
  {"name": "Roman Dolidze", "city": "Batumi", "state": "NaN", "country": "Georgia"},
  {"name": "Hector Lombard", "city": "Havana", "state": "NaN", "country": "Cuba"},
  {"name": "Asadulaev Surkhay", "city": "Makhachkala", "state": "NaN", "country": "Russia"},
  {"name": "Marcio Cromado", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Bob Schirmer", "city": "Chicago", "state": "Illinois", "country": "USA"},
  {"name": "Chris Brennan", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Gao Hua", "city": "Beijing", "state": "NaN", "country": "China"},
  {"name": "Mourat Ozov", "city": "Istanbul", "state": "NaN", "country": "Turkey"},
  {"name": "Rodrigo Artilheiro", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "K. Toida", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Davis Heart", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Davion Peterson", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Manu Garcia", "city": "Barcelona", "state": "NaN", "country": "Spain"},
  {"name": "Dan Martinez", "city": "Tampa", "state": "Florida", "country": "USA"},
  {"name": "Jason Brudvik", "city": "Seattle", "state": "Washington", "country": "USA"},
  {"name": "Jason Ramsterrer", "city": "Denver", "state": "Colorado", "country": "USA"},
  {"name": "Jesse Urholin", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Amanda Leve", "city": "Philadelphia", "state": "Pennsylvania", "country": "USA"},
  {"name": "Rodrigo Caporal", "city": "Santos", "state": "NaN", "country": "Brazil"},
  {"name": "William Tackett", "city": "Austin", "state": "Texas", "country": "USA"},
  {"name": "Mayssa Bastos", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Chris Bright", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Mark Bocek", "city": "Toronto", "state": "Ontario", "country": "Canada"},
  {"name": "Kassim Anan", "city": "Accra", "state": "NaN", "country": "Ghana"},
  {"name": "Chris Weidman", "city": "Baldwin", "state": "New York", "country": "USA"},
  {"name": "Tom Bass", "city": "Salt Lake City", "state": "Utah", "country": "USA"},
  {"name": "Don Ortega", "city": "Albuquerque", "state": "New Mexico", "country": "USA"},
  {"name": "Shinzo Ansai", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Akihiro Gono", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Alexander Savko", "city": "Minsk", "state": "NaN", "country": "Belarus"},
  {"name": "Nicollas Renier", "city": "Paris", "state": "NaN", "country": "France"},
  {"name": "T. Kosaka", "city": "Kyoto", "state": "NaN", "country": "Japan"},
  {"name": "Jehad Hamdan", "city": "Amman", "state": "NaN", "country": "Jordan"},
  {"name": "Mike Van", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Matt Lindland", "city": "Portland", "state": "Oregon", "country": "USA"},
  {"name": "Denis Roberts", "city": "Perth", "state": "NaN", "country": "Australia"},
  {"name": "Daniel Simoes", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Reese Andy", "city": "Seattle", "state": "Washington", "country": "USA"},
  {"name": "Mario Rinaldi", "city": "Naples", "state": "NaN", "country": "Italy"},
  {"name": "Elvis Sinosic", "city": "Sydney", "state": "NaN", "country": "Australia"},
  {"name": "Darren Andy", "city": "Manchester", "state": "NaN", "country": "England"},
  {"name": "Rogent Lorent", "city": "Brussels", "state": "NaN", "country": "Belgium"},
  {"name": "Tomasz Janiszewski", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Jimmy Friedrich", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Josh Saunders", "city": "Dallas", "state": "Texas", "country": "USA"},
  {"name": "Paulo Pinto", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Diego Sanchez", "city": "Albuquerque", "state": "New Mexico", "country": "USA"},
  {"name": "Cameron Earle", "city": "San Francisco", "state": "California", "country": "USA"},
  {"name": "Micah Pittman", "city": "Miami", "state": "Florida", "country": "USA"},
  {"name": "Mikey Burnet", "city": "Tulsa", "state": "Oklahoma", "country": "USA"},
  {"name": "Serguei Onishuk", "city": "Kiev", "state": "NaN", "country": "Ukraine"},
  {"name": "Y. Kohsaka", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Jamie Ballard", "city": "Liverpool", "state": "NaN", "country": "England"},
  {"name": "Daniel Hortegas", "city": "Barcelona", "state": "NaN", "country": "Spain"},
  {"name": "James Poupolo", "city": "Salem", "state": "Oregon", "country": "USA"},
  {"name": "Liu Wen", "city": "Shanghai", "state": "NaN", "country": "China"},
  {"name": "Tomasz Narkun", "city": "Gdańsk", "state": "NaN", "country": "Poland"},
  {"name": "Michael Wilson", "city": "Austin", "state": "Texas", "country": "USA"},
  {"name": "Jason Lees", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Eduardo Rios", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Fabio Gurgel", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Karl Webber", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Egan Inoe", "city": "Honolulu", "state": "Hawaii", "country": "USA"},
  {"name": "Take Hanai", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Muhammad Saleh", "city": "Dubai", "state": "NaN", "country": "UAE"},
  {"name": "Larry Parker", "city": "Atlanta", "state": "Georgia", "country": "USA"},
  {"name": "Renato Verissimo", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Oleg Taktarov", "city": "Moscow", "state": "NaN", "country": "Russia"},
  {"name": "Simon Siasi", "city": "Sydney", "state": "NaN", "country": "Australia"},
  {"name": "Enson Inoe", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Keita Iwamoto", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Owen Livesey", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Giovanna Jara", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Cristiano Lazzarini", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "R. Alvarenga", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Alian Drueco", "city": "Rome", "state": "NaN", "country": "Italy"},
  {"name": "Mikael Knutsson", "city": "Stockholm", "state": "NaN", "country": "Sweden"},
  {"name": "George St", "city": "Montreal", "state": "Quebec", "country": "Canada"},
  {"name": "Yoshiyuki Yoshida", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Morris Clifoni", "city": "Berlin", "state": "NaN", "country": "Germany"},
  {"name": "Allan Teo", "city": "Singapore", "state": "NaN", "country": "Singapore"},
  {"name": "T. Suzuki", "city": "Nagoya", "state": "NaN", "country": "Japan"},
  {"name": "Joey Gilbert", "city": "San Francisco", "state": "California", "country": "USA"},
  {"name": "Rob Di", "city": "Miami", "state": "Florida", "country": "USA"},
  {"name": "D. Marinakis", "city": "Athens", "state": "NaN", "country": "Greece"},
  {"name": "Sotaro Yamada", "city": "Kyoto", "state": "NaN", "country": "Japan"},
  {"name": "Rodney Ellis", "city": "Perth", "state": "NaN", "country": "Australia"},
  {"name": "Bruno Bastos", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Marcos Oliveira", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Anthony Perosh", "city": "Sydney", "state": "NaN", "country": "Australia"},
  {"name": "Kiuma Kunioku", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Mario Miranda", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "George Sotiropoulos", "city": "Melbourne", "state": "NaN", "country": "Australia"},
  {"name": "Kurt Pellegrino", "city": "Belmar", "state": "New Jersey", "country": "USA"},
  {"name": "Keita Nakamura", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Robert Sabaruddin", "city": "Jakarta", "state": "NaN", "country": "Indonesia"},
  {"name": "Van Arsdale", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Mike Whitehead", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Alex Negao", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Miodrag Petkovic", "city": "Belgrade", "state": "NaN", "country": "Serbia"},
  {"name": "J. Pietlainen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Takanori Gomi", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Thomas DeBlass", "city": "Ocean County", "state": "New Jersey", "country": "USA"},
  {"name": "Jorge Britto", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Keller Sodhi", "city": "Delhi", "state": "NaN", "country": "India"},
  {"name": "Youngnam Noh", "city": "Seoul", "state": "NaN", "country": "South Korea"},
  {"name": "Ben Henderson", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Kitner Mendoga", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "H. Sekine", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Mateusz Juskowiak", "city": "Poznań", "state": "NaN", "country": "Poland"},
  {"name": "E. Elgland", "city": "Stockholm", "state": "NaN", "country": "Sweden"},
  {"name": "Eric Dahlberg", "city": "Gothenburg", "state": "NaN", "country": "Sweden"},
  {"name": "Ben Askren", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Doorwang Jeon", "city": "Seoul", "state": "NaN", "country": "South Korea"},
  {"name": "Janus Andrejczuk", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Kenta Iwamoto", "city": "Nagoya", "state": "NaN", "country": "Japan"},
  {"name": "Wagnney Fabiano", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Jacob Rodriguez", "city": "Austin", "state": "Texas", "country": "USA"},
  {"name": "Tom Lawlor", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Jeon Doo", "city": "Seoul", "state": "NaN", "country": "South Korea"},
  {"name": "Shinsho Anzai", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Hidemi Mihara", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Abdulkadirov Magomed", "city": "Makhachkala", "state": "NaN", "country": "Russia"},
  {"name": "Perttu Terpponnen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Teemu Launis", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Mario Delgado", "city": "Quito", "state": "NaN", "country": "Ecuador"},
  {"name": "Darrel Moodley", "city": "Johannesburg", "state": "NaN", "country": "South Africa"},
  {"name": "Kouhei Yasumi", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Frank Trigg", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Rodrigo Modrias", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Fabiano Iha", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Israel Albuquerque", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Chris Brown", "city": "Houston", "state": "Texas", "country": "USA"},
  {"name": "G. Sotiropoulos", "city": "Melbourne", "state": "NaN", "country": "Australia"},
  {"name": "Josh Barnet", "city": "Seattle", "state": "Washington", "country": "USA"},
  {"name": "Y. Setsenko", "city": "Moscow", "state": "NaN", "country": "Russia"},
  {"name": "Marshurenko", "city": "Kyiv", "state": "NaN", "country": "Ukraine"},
  {"name": "M. Van", "city": "Ho Chi Minh City", "state": "NaN", "country": "Vietnam"},
  {"name": "Andy Reese", "city": "Denver", "state": "Colorado", "country": "USA"},
  {"name": "R. Babalu", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Roger Neff", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Luis Orlando", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Toshiyuki Oyama", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Yuta Sasaki", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Travis Lutter", "city": "Dallas", "state": "Texas", "country": "USA"},
  {"name": "Jerry Bolander", "city": "San Francisco", "state": "California", "country": "USA"},
  {"name": "Pete Williams", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Yuki Ozawa", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Asa Fuller", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Sekine Hideki", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Mike Martelle", "city": "Kingston", "state": "NaN", "country": "Canada"},
  {"name": "Kamil Huminski", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Khazmat Stambulov", "city": "Grozny", "state": "NaN", "country": "Russia"},
  {"name": "Jurie Rachel", "city": "Cape Town", "state": "NaN", "country": "South Africa"},
  {"name": "Luis Roberto", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Hiroyuko Abe", "city": "Nagoya", "state": "NaN", "country": "Japan"},
  {"name": "Joe Guilbert", "city": "Boston", "state": "Massachusetts", "country": "USA"},
  {"name": "Greger Forsel", "city": "Stockholm", "state": "NaN", "country": "Sweden"},
  {"name": "Joseph Lee", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Adrian Serrano", "city": "Buenos Aires", "state": "NaN", "country": "Argentina"},
  {"name": "Carlos Newton", "city": "Toronto", "state": "Ontario", "country": "Canada"},
  {"name": "Ahmad Faraj", "city": "Amman", "state": "NaN", "country": "Jordan"},
  {"name": "Gavin Kulper", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Nathan Marquardt", "city": "Denver", "state": "Colorado", "country": "USA"},
  {"name": "Justin Garcia", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Jon Einemo", "city": "Oslo", "state": "NaN", "country": "Norway"},
  {"name": "Travers Grubb", "city": "Chicago", "state": "Illinois", "country": "USA"},
  {"name": "Kim Dong", "city": "Seoul", "state": "NaN", "country": "South Korea"},
  {"name": "C. Jones", "city": "Atlanta", "state": "Georgia", "country": "USA"},
  {"name": "Nieman Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "David Bielkheden", "city": "Stockholm", "state": "NaN", "country": "Sweden"},
  {"name": "Dennis Hallman", "city": "Seattle", "state": "Washington", "country": "USA"},
  {"name": "Joao Roque", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "James Harbison", "city": "Miami", "state": "Florida", "country": "USA"},
  {"name": "Dan Schon", "city": "Phoenix", "state": "Arizona", "country": "USA"},
  {"name": "Juan Valles", "city": "Guatemala City", "state": "NaN", "country": "Guatemala"},
  {"name": "Melchor M.", "city": "Manila", "state": "NaN", "country": "Philippines"},
  {"name": "A. Hamlet", "city": "Oslo", "state": "NaN", "country": "Norway"},
  {"name": "Martin Brown", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Mike Cardosa", "city": "Austin", "state": "Texas", "country": "USA"},
  {"name": "Charles Pearson", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Hiroshi Nakamura", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Joel Tudor", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "David Marinakis", "city": "Athens", "state": "NaN", "country": "Greece"},
  {"name": "Tezekbaev Rasul", "city": "Bishkek", "state": "NaN", "country": "Kyrgyzstan"},
  {"name": "U. Zhakshylyk", "city": "Almaty", "state": "NaN", "country": "Kazakhstan"},
  {"name": "Vernon White", "city": "Las Vegas", "state": "Nevada", "country": "USA"},
  {"name": "Dave Menne", "city": "Minneapolis", "state": "Minnesota", "country": "USA"},
  {"name": "R. Anderson", "city": "London", "state": "NaN", "country": "England"},
  {"name": "T. Yano", "city": "Nagoya", "state": "NaN", "country": "Japan"},
  {"name": "Yuki Sasaki", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "L. Papadopoulis", "city": "Athens", "state": "NaN", "country": "Greece"},
  {"name": "Kouji Kanechika", "city": "Fukuoka", "state": "NaN", "country": "Japan"},
  {"name": "Jorge Santiago", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "I. Praporshchikov", "city": "Moscow", "state": "NaN", "country": "Russia"},
  {"name": "Jose Junior", "city": "Dubai", "state": "NaN", "country": "UAE"},
  {"name": "Milton Vieira", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Isaak Michel", "city": "Sydney", "state": "NaN", "country": "Australia"},
  {"name": "Sanshiro Nakamura", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Chris Wideman", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Luke Costello", "city": "San Francisco", "state": "California", "country": "USA"},
  {"name": "Wang Yan", "city": "Beijing", "state": "NaN", "country": "China"},
  {"name": "P. Ardilla", "city": "Bogotá", "state": "NaN", "country": "Colombia"},
  {"name": "Rumina Sato", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Fernando Vieira", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Hanette Staack", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Jessica Flowers", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Akira Soji", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "Otto Olsen", "city": "Oslo", "state": "NaN", "country": "Norway"},
  {"name": "Renan Sancar", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Mateusz Garmot", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "Kaynan D.", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Jayson Patino", "city": "Orlando", "state": "Florida", "country": "USA"},
  {"name": "Mraz Avdoyan", "city": "Yerevan", "state": "NaN", "country": "Armenia"},
  {"name": "Rodrigo Minotauro", "city": "Salvador", "state": "NaN", "country": "Brazil"},
  {"name": "Tobias G", "city": "Berlin", "state": "NaN", "country": "Germany"},
  {"name": "Kari Petola", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Adele Fornarino", "city": "Rome", "state": "NaN", "country": "Italy"},
  {"name": "Ryan Harvey", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Tom Barlow", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Janne Pietilainen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Ricardo Alves", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Sim Go", "city": "Seoul", "state": "NaN", "country": "South Korea"},
  {"name": "Jason White", "city": "Austin", "state": "Texas", "country": "USA"},
  {"name": "Damon Ramos", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Roan Jucao", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Bruno Chavez", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Luis Brito", "city": "Caracas", "state": "NaN", "country": "Venezuela"},
  {"name": "Fan Yi", "city": "Beijing", "state": "NaN", "country": "China"},
  {"name": "H. Kanehara", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "R. Mashurenko", "city": "Kyiv", "state": "NaN", "country": "Ukraine"},
  {"name": "Tamura", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Hudson Taylor", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "F. Capoane", "city": "Bucharest", "state": "NaN", "country": "Romania"},
  {"name": "Adam Sachnoff", "city": "San Francisco", "state": "California", "country": "USA"},
  {"name": "Genki Sudo", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Robert Sulski", "city": "Warsaw", "state": "NaN", "country": "Poland"},
  {"name": "J. Wakabayashi", "city": "Osaka", "state": "NaN", "country": "Japan"},
  {"name": "D. Hemmings", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Takefuni Hanai", "city": "Fukuoka", "state": "NaN", "country": "Japan"},
  {"name": "Dan Manasoiu", "city": "Bucharest", "state": "NaN", "country": "Romania"},
  {"name": "Livia Giles", "city": "Melbourne", "state": "NaN", "country": "Australia"},
  {"name": "Roman Dolidze", "city": "Tbilisi", "state": "NaN", "country": "Georgia"},
  {"name": "Hector Lombard", "city": "Havana", "state": "NaN", "country": "Cuba"},
  {"name": "Asadulaev Surkhay", "city": "Makhachkala", "state": "NaN", "country": "Russia"},
  {"name": "Marcio Cromado", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Bob Schirmer", "city": "Chicago", "state": "Illinois", "country": "USA"},
  {"name": "Chris Brennan", "city": "Dallas", "state": "Texas", "country": "USA"},
  {"name": "Gao Hua", "city": "Beijing", "state": "NaN", "country": "China"},
  {"name": "Mourat Ozov", "city": "Istanbul", "state": "NaN", "country": "Turkey"},
  {"name": "Rodrigo Artilheiro", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "K. Toida", "city": "Tokyo", "state": "NaN", "country": "Japan"},
  {"name": "Davis Heart", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Davion Peterson", "city": "Miami", "state": "Florida", "country": "USA"},
  {"name": "Manu Garcia", "city": "Barcelona", "state": "NaN", "country": "Spain"},
  {"name": "Dan Martinez", "city": "Orlando", "state": "Florida", "country": "USA"},
  {"name": "Jason Brudvik", "city": "Seattle", "state": "Washington", "country": "USA"},
  {"name": "Jason Ramsterrer", "city": "Denver", "state": "Colorado", "country": "USA"},
  {"name": "Jesse Urholin", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Amanda Leve", "city": "Philadelphia", "state": "Pennsylvania", "country": "USA"},
  {"name": "Rodrigo Caporal", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "William Tackett", "city": "Austin", "state": "Texas", "country": "USA"},
  {"name": "Mayssa Bastos", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Glover Teixeira", "city": "Sobrália", "state": "NaN", "country": "Brazil"},
  {"name": "Hannette Staack", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Gabrielle McComb", "city": "Manaus", "state": "NaN", "country": "Brazil"},
  {"name": "Bianca Mesquita", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Luiza Monteiro", "city": "Recife", "state": "NaN", "country": "Brazil"},
  {"name": "Jessica Oliveira", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Gabrielle Garcia", "city": "Porto Alegre", "state": "NaN", "country": "Brazil"},
  {"name": "Nathalie Ribeiro", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Beatriz Mesquita", "city": "Niterói", "state": "NaN", "country": "Brazil"},
  {"name": "Claudia Do Val", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Tammi Musumeci", "city": "Marlboro", "state": "New Jersey", "country": "USA"},
  {"name": "Tayane Porfirio", "city": "Brasília", "state": "NaN", "country": "Brazil"},
  {"name": "Michelle Nicolini", "city": "Itu", "state": "NaN", "country": "Brazil"},
  {"name": "Kyra Gracie", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Venla Luukkonen", "city": "Helsinki", "state": "NaN", "country": "Finland"},
  {"name": "Dominyka Obelenyte", "city": "Kaunas", "state": "NaN", "country": "Lithuania"},
  {"name": "Karen Antunes", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Luanna Alzuguir", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Stefanie Egger", "city": "Bern", "state": "NaN", "country": "Switzerland"},
  {"name": "Talita Nogueira", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Amanda Santana", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Monique Elias", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Luiza Saffre", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Thamara Silva", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Maria Malyjasiak", "city": "Wrocław", "state": "NaN", "country": "Poland"},
  {"name": "Julia Boscher", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Talita Treta", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Penny Thomas", "city": "Cape Town", "state": "NaN", "country": "South Africa"},
  {"name": "Ashley Williams", "city": "Swansea", "state": "NaN", "country": "Wales"},
  {"name": "Eleftheria Christodoulou", "city": "Athens", "state": "NaN", "country": "Greece"},
  {"name": "Magid Hage", "city": "Beirut", "state": "NaN", "country": "Lebanon"},
  {"name": "Ross Nicholls", "city": "London", "state": "NaN", "country": "England"},
  {"name": "Marcelo Garcia", "city": "Formiga", "state": "NaN", "country": "Brazil"},
  {"name": "Andre Galvao", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Rodolfo Vieira", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Renato Canuto", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Victor Hugo", "city": "Fortaleza", "state": "NaN", "country": "Brazil"},
  {"name": "Lucas Lepri", "city": "Uberlândia", "state": "NaN", "country": "Brazil"},
  {"name": "Felipe Pena", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Jackson Sousa", "city": "Rio de Janeiro", "state": "NaN", "country": "Brazil"},
  {"name": "Kaynan Duarte", "city": "São Paulo", "state": "NaN", "country": "Brazil"},
  {"name": "Tye Ruotolo", "city": "Huntington Beach", "state": "California", "country": "USA"},
  {"name": "Kade Ruotolo", "city": "Huntington Beach", "state": "California", "country": "USA"},
  {"name": "Matheus Diniz", "city": "Belo Horizonte", "state": "NaN", "country": "Brazil"},
  {"name": "Gordon Ryan", "city": "Monroe Township", "state": "New Jersey", "country": "USA"},
  {"name": "Nicky Ryan", "city": "Monroe Township", "state": "New Jersey", "country": "USA"},
  {"name": "Gianni Grippo", "city": "New York City", "state": "New York", "country": "USA"},
  {"name": "Gary Tonon", "city": "New Brunswick", "state": "New Jersey", "country": "USA"},
  {"name": "Craig Jones", "city": "Adelaide", "state": "NaN", "country": "Australia"},
  {"name": "Lachlan Giles", "city": "Melbourne", "state": "NaN", "country": "Australia"},
  {"name": "John Danaher", "city": "Whangārei", "state": "NaN", "country": "New Zealand"},
  {"name": "Eddie Bravo", "city": "Santa Ana", "state": "California", "country": "USA"},
  {"name": "Dean Lister", "city": "San Diego", "state": "California", "country": "USA"},
  {"name": "Keanu Subba", "city": "Kuala Lumpur", "state": "NaN", "country": "Malaysia"},
  {"name": "Demi Lovato", "city": "Los Angeles", "state": "California", "country": "USA"},
  {"name": "Shinya Aoki", "city": "Shizuoka", "state": "NaN", "country": "Japan"}
  
  
  


  
  
  
    
    
    
    
    
]
len(fighters_info)

686

In [6]:
fighters_info = pd.DataFrame(fighters_info)

In [7]:
fighters_info.head()

                name                       city         state country
0     Murilo Santana                  São Paulo           NaN  Brazil
1  Nicholas Meregali  Santo Antônio da Patrulha           NaN  Brazil
2     Nick Rodriguez               Philadelphia  Pennsylvania     USA
3       Otavio Sousa                     Recife           NaN  Brazil
4    Orlando Sanchez                Los Angeles    California     USA

In [8]:
fighters_info['name'].nunique()

622

In [9]:
fighters = pd.merge(fighters, fighters_info, on="name", how="left")
fighters.head()

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,champion,custom_score,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country
0,Murilo Santana,0.454545,11.0,0.181818,0.181818,0.090909,7.0,-0.272727,0.000000,1.571429,...,0,-0.165699,1,0,5.0,2009,0,São Paulo,NaN,Brazil
1,Nicholas Meregali,0.750000,8.0,0.125000,0.250000,0.250000,2.0,0.125000,-0.375000,4.000000,...,0,1.977330,1,0,6.0,2022,0,Santo Antônio da Patrulha,NaN,Brazil
2,Nick Rodriguez,0.700000,10.0,0.100000,0.400000,0.200000,4.0,2.300000,-0.200000,2.500000,...,0,0.854628,1,0,7.0,2019,0,Philadelphia,Pennsylvania,USA
3,Otavio Sousa,0.625000,8.0,0.375000,0.125000,0.125000,4.0,-0.750000,0.500000,2.000000,...,0,0.567981,2,0,5.0,2013,0,Recife,NaN,Brazil
4,Orlando Sanchez,0.692308,13.0,0.153846,0.153846,0.384615,8.0,-0.384615,-0.461538,1.625000,...,1,0.424658,2,0,9.0,2013,0,Los Angeles,California,USA

In [10]:
null_cities = fighters[fighters['city'].isna()]
null_cities

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,champion,custom_score,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country
185,Ruslam Chsiev,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0,-0.411396,0,0,1.0,2017,0,NaN,NaN,NaN
194,Eoghan OFlannagan,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.411396,0,0,1.0,2022,0,NaN,NaN,NaN
328,Ana Carolina,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.029200,0,0,0.0,2019,1,NaN,NaN,NaN
398,T. Pyylampi,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.411396,0,0,0.0,2017,0,NaN,NaN,NaN
399,Wellington Dias,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.411396,0,0,0.0,1999,0,NaN,NaN,NaN
400,Akira Shouji,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.411396,0,0,0.0,1999,0,NaN,NaN,NaN
410,Nicholas Renier,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.411396,0,0,0.0,2015,0,NaN,NaN,NaN
411,N. Uematsu,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.315847,0,0,0.0,2001,0,NaN,NaN,NaN
412,Mike Mrkulic,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.315847,0,0,0.0,2003,0,NaN,NaN,NaN
413,Eddie Sanchez,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.411396,0,0,0.0,2007,0,NaN,NaN,NaN
414,Yoshitomi Mishima,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.315847,0,0,0.0,2007,0,NaN,NaN,NaN
415,Tetsu Suzuko,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,0.448545,0,0,0.0,2007,0,NaN,NaN,NaN
416,Rikako Yuasa,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,-0.315847,0,0,0.0,2019,1,NaN,NaN,NaN

In [11]:
duplicates = fighters[fighters.duplicated(subset=['name'])]
print(duplicates)

                name  win_ratio  total_fights  sub_win_ratio  point_win_ratio  \
14    Rodolfo Vieira   0.800000          10.0       0.400000         0.300000
26       Craig Jones   0.642857          14.0       0.571429         0.000000
35       Eddie Bravo   0.666667           3.0       0.666667         0.000000
37       Dean Lister   0.678571          28.0       0.571429         0.107143
42        Gary Tonon   0.444444          18.0       0.277778         0.166667
..               ...        ...           ...            ...              ...
669    Jesse Urholin   0.000000           1.0       0.000000         0.000000
671      Amanda Leve   0.000000           1.0       0.000000         0.000000
673  Rodrigo Caporal   0.000000           1.0       0.000000         0.000000
675  William Tackett   0.000000           1.0       0.000000         0.000000
677    Mayssa Bastos   0.000000           1.0       0.000000         0.000000

     decision_win_ratio  n_editions_competed  scored_points_per_fight  \
14             0.100000                  4.0                 1.000000
26             0.071429                  6.0                -0.714286
35             0.000000                  2.0                -0.666667
37             0.000000                 12.0                -0.464286
42             0.000000                  9.0                -0.444444
..                  ...                  ...                      ...
669            0.000000                  1.0                 0.000000
671            0.000000                  1.0                 0.000000
673            0.000000                  1.0                 0.000000
675            0.000000                  1.0                 0.000000
677            0.000000                  1.0                 0.000000

     suffered_points_per_fight  fights_per_edition  ... champion custom_score  \
14                   -0.400000            2.500000  ...        1     0.878516
26                    1.357143            2.333333  ...        0     0.671493
35                    4.666667            1.500000  ...        0    -0.124749
37                    0.178571            2.333333  ...        1     1.021839
42                    0.388889            2.000000  ...        0     0.045116
..                         ...                 ...  ...      ...          ...
669                   0.000000            1.000000  ...        0    -0.411396
671                   0.000000            1.000000  ...        0    -0.315847
673                   0.000000            1.000000  ...        0    -0.411396
675                   0.000000            1.000000  ...        0    -0.411396
677                   0.000000            1.000000  ...        0    -0.315847

     n_different_subs  fought_superfight  total_wins  debut_year  female  \
14                  4                  0         8.0        2011       0
26                  6                  0         9.0        2017       0
35                  2                  0         2.0        2003       0
37                  8                  0        19.0        2001       0
42                  3                  0         8.0        2013       0
..                ...                ...         ...         ...     ...
669                 0                  0         0.0        2017       0
671                 0                  0         0.0        2019       1
673                 0                  0         0.0        2013       0
675                 0                  0         0.0        2022       0
677                 0                  0         0.0        2022       1

               city         state    country
14   Rio de Janeiro           NaN     Brazil
26         Adelaide           NaN  Australia
35        Santa Ana    California        USA
37        San Diego    California        USA
42    New Brunswick    New Jersey        USA
..              ...           ...        ...
669        Helsinki           NaN    Finland
671    Philadelphia  Pennsylvania        USA
673  Rio de Janeiro           NaN     Brazil
675          Austin         Texas        USA
677         Niterói           NaN     Brazil

[64 rows x 28 columns]

In [12]:
print(null_cities['name'])

185        Ruslam Chsiev
194    Eoghan OFlannagan
328         Ana Carolina
398          T. Pyylampi
399      Wellington Dias
400         Akira Shouji
410      Nicholas Renier
411           N. Uematsu
412         Mike Mrkulic
413        Eddie Sanchez
414    Yoshitomi Mishima
415         Tetsu Suzuko
416         Rikako Yuasa
Name: name, dtype: object

In [13]:
fighters = fighters.drop_duplicates(subset=['name'])
print(fighters.nunique())

name                         614
win_ratio                     55
total_fights                  30
sub_win_ratio                 51
point_win_ratio               56
decision_win_ratio            30
n_editions_competed           14
scored_points_per_fight       81
suffered_points_per_fight     88
fights_per_edition            45
favorite_target                5
most_vulnerable                5
n_weight_classes               4
main_weight_class              5
avg_match_importance          70
highest_match_importance       6
open_weight_ratio             41
n_titles                       7
champion                       2
custom_score                 101
n_different_subs               9
fought_superfight              1
total_wins                    24
debut_year                    14
female                         2
city                         185
state                         32
country                       57
dtype: int64

In [14]:
fighters.head(30)

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,champion,custom_score,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country
0,Murilo Santana,0.454545,11.0,0.181818,0.181818,0.090909,7.0,-0.272727,0.000000,1.571429,...,0,-0.165699,1,0,5.0,2009,0,São Paulo,NaN,Brazil
1,Nicholas Meregali,0.750000,8.0,0.125000,0.250000,0.250000,2.0,0.125000,-0.375000,4.000000,...,0,1.977330,1,0,6.0,2022,0,Santo Antônio da Patrulha,NaN,Brazil
2,Nick Rodriguez,0.700000,10.0,0.100000,0.400000,0.200000,4.0,2.300000,-0.200000,2.500000,...,0,0.854628,1,0,7.0,2019,0,Philadelphia,Pennsylvania,USA
3,Otavio Sousa,0.625000,8.0,0.375000,0.125000,0.125000,4.0,-0.750000,0.500000,2.000000,...,0,0.567981,2,0,5.0,2013,0,Recife,NaN,Brazil
4,Orlando Sanchez,0.692308,13.0,0.153846,0.153846,0.384615,8.0,-0.384615,-0.461538,1.625000,...,1,0.424658,2,0,9.0,2013,0,Los Angeles,California,USA
5,Pablo Mantovani,0.500000,6.0,0.000000,0.333333,0.166667,4.0,2.000000,1.166667,1.500000,...,0,-0.029200,0,0,3.0,2017,0,São Paulo,NaN,Brazil
6,Pablo Popovitch,0.730769,26.0,0.115385,0.576923,0.038462,12.0,0.269231,-0.576923,2.166667,...,1,0.846666,2,0,19.0,2003,0,Rio de Janeiro,NaN,Brazil
7,Paul Schreiner,0.500000,4.0,0.000000,0.500000,0.000000,2.0,1.250000,-0.500000,2.000000,...,0,0.305221,0,0,2.0,2022,0,Santa Cruz,California,USA
8,Paulo Miyao,0.750000,8.0,0.000000,0.750000,0.000000,4.0,4.750000,0.125000,2.000000,...,0,0.735192,0,0,6.0,2017,0,Andirá,NaN,Brazil
9,Rida Haisam,0.333333,3.0,0.333333,0.000000,0.000000,2.0,-0.666667,0.000000,1.500000,...,0,-0.363622,1,0,1.0,2022,0,Accra,NaN,Ghana
10,Roberto Abreu,0.689655,29.0,0.103448,0.517241,0.068966,13.0,0.103448,-0.275862,2.230769,...,1,0.874841,2,0,20.0,2009,0,Campo Grande,NaN,Brazil
11,Roberto Jimenez,0.333333,3.0,0.333333,0.000000,0.000000,2.0,0.000000,3.666667,1.500000,...,0,-0.363622,1,0,1.0,2022,0,Guayaquil,NaN,Ecuador
12,Robson Moura,0.625000,8.0,0.125000,0.375000,0.125000,4.0,0.125000,-0.375000,2.000000,...,0,0.520207,1,0,5.0,2001,0,Teresópolis,NaN,Brazil
13,Rodolfo Vieira,0.800000,10.0,0.400000,0.300000,0.100000,4.0,1.000000,-0.400000,2.500000,...,1,0.878516,4,0,8.0,2011,0,Rio de Janeiro,NaN,Brazil
15,Rodrigo Medeiros,0.375000,8.0,0.000000,0.375000,0.000000,4.0,1.625000,1.250000,2.000000,...,0,-0.053087,0,0,3.0,2000,0,Rio de Janeiro,NaN,Brazil
16,Roger Gracie,0.923077,13.0,0.615385,0.307692,0.000000,4.0,0.307692,-0.538462,3.250000,...,1,3.362791,4,0,12.0,2003,0,Rio de Janeiro,NaN,Brazil
17,Romulo Barral,0.555556,18.0,0.333333,0.222222,0.000000,10.0,-0.833333,-0.444444,1.800000,...,1,0.295667,4,0,10.0,2007,0,Belo Horizonte,NaN,Brazil
18,Ronaldo Souza,0.785714,14.0,0.428571,0.357143,0.000000,6.0,1.285714,-0.071429,2.333333,...,1,2.279901,4,0,11.0,2003,0,Vila Velha,NaN,Brazil
19,Roosevelt Sousa,0.666667,3.0,0.333333,0.333333,0.000000,2.0,0.000000,-0.666667,1.500000,...,0,-0.124749,1,0,2.0,2022,0,Natal,NaN,Brazil
20,Adam Wardzinski,0.500000,2.0,0.000000,0.000000,0.500000,2.0,-1.000000,-1.000000,1.000000,...,0,-0.363622,0,0,1.0,2019,0,Poznań,NaN,Poland
21,Braulio Estima,0.750000,16.0,0.500000,0.187500,0.000000,6.0,-0.750000,-0.937500,2.666667,...,1,2.534699,5,0,12.0,2005,0,Recife,NaN,Brazil
22,Celso Vinicius,0.400000,5.0,0.000000,0.200000,0.200000,4.0,0.200000,0.800000,1.250000,...,0,-0.363622,0,0,2.0,2017,0,São Paulo,NaN,Brazil
23,Claudio Calasans,0.583333,12.0,0.166667,0.083333,0.333333,6.0,-0.666667,0.916667,2.000000,...,1,0.910365,2,0,7.0,2011,0,São Paulo,NaN,Brazil
24,Bruno Frazatto,0.428571,7.0,0.142857,0.142857,0.142857,4.0,-0.142857,1.142857,1.750000,...,0,0.209672,1,0,3.0,2011,0,São Paulo,NaN,Brazil
25,Craig Jones,0.642857,14.0,0.571429,0.000000,0.071429,6.0,-0.714286,1.357143,2.333333,...,0,0.671493,6,0,9.0,2017,0,Adelaide,NaN,Australia
27,Brianna Ste-Marie,0.666667,3.0,0.000000,0.666667,0.000000,2.0,2.333333,3.333333,1.500000,...,0,0.830741,0,0,2.0,2022,1,Montreal,NaN,Canada
28,Dante Leon,0.625000,8.0,0.250000,0.250000,0.125000,4.0,0.125000,-0.375000,2.000000,...,0,0.520207,1,0,5.0,2019,0,Windsor,NaN,Canada
29,Davi Ramos,1.000000,4.0,0.750000,0.250000,0.000000,1.0,0.000000,0.000000,4.000000,...,1,3.601663,2,0,4.0,2015,0,Rio de Janeiro,NaN,Brazil
30,David Terrell,0.750000,4.0,0.250000,0.500000,0.000000,2.0,-1.000000,-1.000000,2.000000,...,0,0.735192,1,0,3.0,2003,0,Santa Rosa,California,USA
31,Demian Maia,0.875000,8.0,0.125000,0.750000,0.000000,3.0,0.250000,-0.500000,2.666667,...,1,1.754382,1,0,7.0,2005,0,São Paulo,NaN,Brazil

In [15]:
us_fighters = fighters[fighters['country'] == 'USA']
world_fighters = fighters[fighters['country'] != 'USA']

In [16]:
us_fighters.head(20)

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,champion,custom_score,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country
2,Nick Rodriguez,0.700000,10.0,0.100000,0.400000,0.200000,4.0,2.300000,-0.200000,2.500000,...,0,0.854628,1,0,7.0,2019,0,Philadelphia,Pennsylvania,USA
4,Orlando Sanchez,0.692308,13.0,0.153846,0.153846,0.384615,8.0,-0.384615,-0.461538,1.625000,...,1,0.424658,2,0,9.0,2013,0,Los Angeles,California,USA
7,Paul Schreiner,0.500000,4.0,0.000000,0.500000,0.000000,2.0,1.250000,-0.500000,2.000000,...,0,0.305221,0,0,2.0,2022,0,Santa Cruz,California,USA
30,David Terrell,0.750000,4.0,0.250000,0.500000,0.000000,2.0,-1.000000,-1.000000,2.000000,...,0,0.735192,1,0,3.0,2003,0,Santa Rosa,California,USA
34,Eddie Bravo,0.666667,3.0,0.666667,0.000000,0.000000,2.0,-0.666667,4.666667,1.500000,...,0,-0.124749,2,0,2.0,2003,0,Santa Ana,California,USA
36,Dean Lister,0.678571,28.0,0.571429,0.107143,0.000000,12.0,-0.464286,0.178571,2.333333,...,1,1.021839,8,0,19.0,2001,0,San Diego,California,USA
38,DeAlonzio Jackson,0.400000,5.0,0.000000,0.200000,0.200000,5.0,0.400000,0.000000,1.000000,...,0,-0.373177,0,0,2.0,2013,0,Chicago,Illinois,USA
41,Gary Tonon,0.444444,18.0,0.277778,0.166667,0.000000,9.0,-0.444444,0.388889,2.000000,...,0,0.045116,3,0,8.0,2013,0,New Brunswick,New Jersey,USA
43,Giancarlo Bodoni,0.833333,6.0,0.666667,0.166667,0.000000,2.0,0.666667,0.333333,3.000000,...,1,1.642908,4,0,5.0,2022,0,New York City,New York,USA
44,Gianni Grippo,0.333333,3.0,0.000000,0.333333,0.000000,3.0,0.666667,2.333333,1.000000,...,0,-0.379547,0,0,1.0,2015,0,New York City,New York,USA
47,Gordon Ryan,0.952381,21.0,0.714286,0.142857,0.095238,4.0,-0.285714,-0.523810,5.250000,...,1,5.417095,7,0,20.0,2017,0,Monroe Township,New Jersey,USA
49,Justin Rader,0.625000,8.0,0.000000,0.500000,0.125000,6.0,-0.500000,-0.875000,1.333333,...,0,0.002649,0,0,5.0,2009,0,Oklahoma City,Oklahoma,USA
50,Keenan Cornelius,0.750000,16.0,0.250000,0.437500,0.062500,6.0,1.687500,-0.250000,2.666667,...,0,1.181088,4,0,12.0,2013,0,Hilo,Hawaii,USA
62,Ryan Hall,0.600000,5.0,0.000000,0.600000,0.000000,4.0,0.400000,0.800000,1.250000,...,0,0.066349,0,0,3.0,2009,0,Falls Church,Virginia,USA
63,Tye Ruotolo,0.500000,8.0,0.125000,0.250000,0.125000,4.0,0.000000,0.375000,2.000000,...,0,0.090236,1,0,4.0,2019,0,Huntington Beach,California,USA
65,Tim Spriggs,0.500000,6.0,0.333333,0.166667,0.000000,4.0,0.333333,-0.666667,1.500000,...,0,-0.339735,1,0,3.0,2017,0,Baltimore,Maryland,USA
68,Geovanny Martinez,0.375000,8.0,0.125000,0.250000,0.000000,6.0,0.750000,1.000000,1.333333,...,0,-0.156599,1,0,3.0,2015,0,San Diego,California,USA
69,Jared Dopp,0.533333,15.0,0.066667,0.400000,0.066667,7.0,-0.333333,-0.466667,2.142857,...,0,0.352996,1,0,8.0,2013,0,Oklahoma City,Oklahoma,USA
71,Mansher Khera,0.500000,2.0,0.000000,0.500000,0.000000,2.0,0.500000,-0.500000,1.000000,...,0,-0.363622,0,0,1.0,2017,0,New York City,New York,USA
73,AJ Agazarm,0.444444,9.0,0.000000,0.222222,0.222222,6.0,-0.222222,-0.333333,1.500000,...,0,0.018574,0,0,4.0,2013,0,Cleveland,Ohio,USA

In [17]:
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
import time

# Initialize the geolocator
geolocator = Nominatim(user_agent="geoapiExercises")

location_cache = {}

def get_lat_long_cached(row):
    location_key = f"{row['city']}, {row['country']}"
    if location_key in location_cache:
        return location_cache[location_key]
    try:
        location = geolocator.geocode(location_key)
        if location:
            location_cache[location_key] = (location.latitude, location.longitude)
            return location.latitude, location.longitude
    except Exception as e:
        print(f"Error: {e}")
    location_cache[location_key] = (None, None)
    return None, None

world_fighters[['latitude', 'longitude']] = world_fighters.apply(
    lambda row: get_lat_long_cached(row), axis=1, result_type="expand"
)

KeyboardInterrupt:

In [ ]:
world_fighters

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country,latitude,longitude
0,Murilo Santana,0.454545,11.0,0.181818,0.181818,0.090909,7.0,-0.272727,0.000000,1.571429,...,1,0,5.0,2009,0,São Paulo,NaN,Brazil,-1.204322,-47.158394
1,Nicholas Meregali,0.750000,8.0,0.125000,0.250000,0.250000,2.0,0.125000,-0.375000,4.000000,...,1,0,6.0,2022,0,Santo Antônio da Patrulha,NaN,Brazil,-29.826768,-50.517489
3,Otavio Sousa,0.625000,8.0,0.375000,0.125000,0.125000,4.0,-0.750000,0.500000,2.000000,...,2,0,5.0,2013,0,Recife,NaN,Brazil,-8.058493,-34.884819
5,Pablo Mantovani,0.500000,6.0,0.000000,0.333333,0.166667,4.0,2.000000,1.166667,1.500000,...,0,0,3.0,2017,0,São Paulo,NaN,Brazil,-1.204322,-47.158394
6,Pablo Popovitch,0.730769,26.0,0.115385,0.576923,0.038462,12.0,0.269231,-0.576923,2.166667,...,2,0,19.0,2003,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,K. Toida,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2003,0,Tokyo,NaN,Japan,35.676860,139.763895
660,Manu Garcia,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2000,0,Barcelona,NaN,Spain,41.382894,2.177432
668,Jesse Urholin,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2017,0,Helsinki,NaN,Finland,60.167488,24.942747
672,Rodrigo Caporal,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2013,0,Santos,NaN,Brazil,-23.933599,-46.328640
676,Mayssa Bastos,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2022,1,Niterói,NaN,Brazil,-22.888400,-43.114700

In [ ]:
nan_count = world_fighters['latitude'].isna().sum()
nan_count

np.int64(0)

In [ ]:
# Apply the function to the DataFrame
us_fighters[['latitude', 'longitude']] = us_fighters.apply(lambda row: get_lat_long(row), axis=1, result_type="expand")

# Check the DataFrame
print(us_fighters)

                 name  win_ratio  total_fights  sub_win_ratio  \
2      Nick Rodriguez   0.700000          10.0       0.100000
4     Orlando Sanchez   0.692308          13.0       0.153846
7      Paul Schreiner   0.500000           4.0       0.000000
30      David Terrell   0.750000           4.0       0.250000
34        Eddie Bravo   0.666667           3.0       0.666667
..                ...        ...           ...            ...
662      Dan Martinez   0.000000           1.0       0.000000
664     Jason Brudvik   0.000000           1.0       0.000000
666  Jason Ramsterrer   0.000000           1.0       0.000000
670       Amanda Leve   0.000000           1.0       0.000000
674   William Tackett   0.000000           1.0       0.000000

     point_win_ratio  decision_win_ratio  n_editions_competed  \
2           0.400000            0.200000                  4.0
4           0.153846            0.384615                  8.0
7           0.500000            0.000000                  2.0
30          0.500000            0.000000                  2.0
34          0.000000            0.000000                  2.0
..               ...                 ...                  ...
662         0.000000            0.000000                  1.0
664         0.000000            0.000000                  1.0
666         0.000000            0.000000                  1.0
670         0.000000            0.000000                  1.0
674         0.000000            0.000000                  1.0

     scored_points_per_fight  suffered_points_per_fight  fights_per_edition  \
2                   2.300000                  -0.200000               2.500
4                  -0.384615                  -0.461538               1.625
7                   1.250000                  -0.500000               2.000
30                 -1.000000                  -1.000000               2.000
34                 -0.666667                   4.666667               1.500
..                       ...                        ...                 ...
662                 0.000000                   0.000000               1.000
664                 0.000000                   0.000000               1.000
666                 0.000000                   0.000000               1.000
670                 0.000000                   0.000000               1.000
674                 0.000000                   0.000000               1.000

     ... n_different_subs fought_superfight  total_wins  debut_year  female  \
2    ...                1                 0         7.0        2019       0
4    ...                2                 0         9.0        2013       0
7    ...                0                 0         2.0        2022       0
30   ...                1                 0         3.0        2003       0
34   ...                2                 0         2.0        2003       0
..   ...              ...               ...         ...         ...     ...
662  ...                0                 0         0.0        2019       0
664  ...                0                 0         0.0        2005       0
666  ...                0                 0         0.0        2003       0
670  ...                0                 0         0.0        2019       1
674  ...                0                 0         0.0        2022       0

             city         state  country   latitude   longitude
2    Philadelphia  Pennsylvania      USA  39.952724  -75.163526
4     Los Angeles    California      USA  34.053691 -118.242766
7      Santa Cruz    California      USA  37.050096 -121.990590
30     Santa Rosa    California      USA  38.440492 -122.714105
34      Santa Ana    California      USA  33.749495 -117.873221
..            ...           ...      ...        ...         ...
662         Tampa       Florida      USA  27.947760  -82.458444
664       Seattle    Washington      USA  47.603832 -122.330062
666        Denver      Colorado      USA  39.739236 -104.984862
670  Philadelphia  Pennsylvania      USA  39.952724  -75.163526
674        Austin         Texas      USA  30.271129  -97.743700

[159 rows x 30 columns]

/var/folders/kf/sp0jlhvs3yb2h_z31jyqkzrc0000gn/T/ipykernel_49318/2424407138.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_fighters[['latitude', 'longitude']] = us_fighters.apply(lambda row: get_lat_long(row), axis=1, result_type="expand")
/var/folders/kf/sp0jlhvs3yb2h_z31jyqkzrc0000gn/T/ipykernel_49318/2424407138.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_fighters[['latitude', 'longitude']] = us_fighters.apply(lambda row: get_lat_long(row), axis=1, result_type="expand")

In [ ]:
world_fighters.loc[:, ['latitude', 'longitude']] = world_fighters.apply(
    lambda row: get_lat_long(row), axis=1, result_type="expand"
)

In [ ]:
world_fighters

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country,latitude,longitude
0,Murilo Santana,0.454545,11.0,0.181818,0.181818,0.090909,7.0,-0.272727,0.000000,1.571429,...,1,0,5.0,2009,0,São Paulo,NaN,Brazil,NaN,NaN
1,Nicholas Meregali,0.750000,8.0,0.125000,0.250000,0.250000,2.0,0.125000,-0.375000,4.000000,...,1,0,6.0,2022,0,Santo Antônio da Patrulha,NaN,Brazil,NaN,NaN
3,Otavio Sousa,0.625000,8.0,0.375000,0.125000,0.125000,4.0,-0.750000,0.500000,2.000000,...,2,0,5.0,2013,0,Recife,NaN,Brazil,NaN,NaN
5,Pablo Mantovani,0.500000,6.0,0.000000,0.333333,0.166667,4.0,2.000000,1.166667,1.500000,...,0,0,3.0,2017,0,São Paulo,NaN,Brazil,NaN,NaN
6,Pablo Popovitch,0.730769,26.0,0.115385,0.576923,0.038462,12.0,0.269231,-0.576923,2.166667,...,2,0,19.0,2003,0,Rio de Janeiro,NaN,Brazil,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,K. Toida,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2003,0,Tokyo,NaN,Japan,NaN,NaN
660,Manu Garcia,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2000,0,Barcelona,NaN,Spain,NaN,NaN
668,Jesse Urholin,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2017,0,Helsinki,NaN,Finland,NaN,NaN
672,Rodrigo Caporal,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2013,0,Santos,NaN,Brazil,NaN,NaN
676,Mayssa Bastos,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,...,0,0,0.0,2022,1,Niterói,NaN,Brazil,NaN,NaN

In [ ]:
location = geolocator.geocode("São Paulo, Brazil")
print(location.latitude, location.longitude)

-1.2043218 -47.1583944

In [ ]:
fighters.to_csv('fighters.csv', index=False)

In [ ]:
fighters['location'] = fighters['city'] + ', ' + fighters['country']
fighters.to_csv('fighters.csv', index=False)

In [106]:
import pandas as pd

# Combine the two DataFrames
all_fighters = pd.concat([us_fighters, world_fighters], axis=0, ignore_index=True)
all_fighters.to_csv('fighters.csv', index=False)

# Display the combined DataFrame
print(all_fighters)

                name  win_ratio  total_fights  sub_win_ratio  point_win_ratio  \
0     Nick Rodriguez   0.700000          10.0       0.100000         0.400000
1    Orlando Sanchez   0.692308          13.0       0.153846         0.153846
2     Paul Schreiner   0.500000           4.0       0.000000         0.500000
3      David Terrell   0.750000           4.0       0.250000         0.500000
4        Eddie Bravo   0.666667           3.0       0.666667         0.000000
..               ...        ...           ...            ...              ...
609         K. Toida   0.000000           1.0       0.000000         0.000000
610      Manu Garcia   0.000000           1.0       0.000000         0.000000
611    Jesse Urholin   0.000000           1.0       0.000000         0.000000
612  Rodrigo Caporal   0.000000           1.0       0.000000         0.000000
613    Mayssa Bastos   0.000000           1.0       0.000000         0.000000

     decision_win_ratio  n_editions_competed  scored_points_per_fight  \
0              0.200000                  4.0                 2.300000
1              0.384615                  8.0                -0.384615
2              0.000000                  2.0                 1.250000
3              0.000000                  2.0                -1.000000
4              0.000000                  2.0                -0.666667
..                  ...                  ...                      ...
609            0.000000                  1.0                 0.000000
610            0.000000                  1.0                 0.000000
611            0.000000                  1.0                 0.000000
612            0.000000                  1.0                 0.000000
613            0.000000                  1.0                 0.000000

     suffered_points_per_fight  fights_per_edition  ... n_different_subs  \
0                    -0.200000               2.500  ...                1
1                    -0.461538               1.625  ...                2
2                    -0.500000               2.000  ...                0
3                    -1.000000               2.000  ...                1
4                     4.666667               1.500  ...                2
..                         ...                 ...  ...              ...
609                   0.000000               1.000  ...                0
610                   0.000000               1.000  ...                0
611                   0.000000               1.000  ...                0
612                   0.000000               1.000  ...                0
613                   0.000000               1.000  ...                0

    fought_superfight  total_wins  debut_year  female          city  \
0                   0         7.0        2019       0  Philadelphia
1                   0         9.0        2013       0   Los Angeles
2                   0         2.0        2022       0    Santa Cruz
3                   0         3.0        2003       0    Santa Rosa
4                   0         2.0        2003       0     Santa Ana
..                ...         ...         ...     ...           ...
609                 0         0.0        2003       0         Tokyo
610                 0         0.0        2000       0     Barcelona
611                 0         0.0        2017       0      Helsinki
612                 0         0.0        2013       0        Santos
613                 0         0.0        2022       1       Niterói

            state  country   latitude   longitude
0    Pennsylvania      USA  39.952724  -75.163526
1      California      USA  34.053691 -118.242766
2      California      USA  37.050096 -121.990590
3      California      USA  38.440492 -122.714105
4      California      USA  33.749495 -117.873221
..            ...      ...        ...         ...
609           NaN    Japan  35.676860  139.763895
610           NaN    Spain  41.382894    2.177432
611           NaN  Finland  60.167488   24.942747
612           NaN   Brazil -23.933599  -46.328640
613           NaN   Brazil -22.888400  -43.114700

[614 rows x 30 columns]